task 2 is completed
AlinaVasylieva/flashcards pull request #2
Opened 2016-10-12 20:57 UTC by AlinaVasylieva

Cards DB is created
Cards are added to DB
Cards review_date format is changed

2016-10-12 21:39 UTC, IvanShamatov requested changes
Не вижу ни миграций, ни моделей. Задача явно не завершена

2016-10-12 21:39 UTC, IvanShamatov commented on config/routes.rb
> +  get '/cards/:id' => 'cards#show'
почитай про resources еще раз, предпочтительнее использовать resources (намекаю на restful)

2016-10-13 09:55 UTC, IvanShamatov requested changes
Вот еще мои замечания, в целом всё норм, косметика...

2016-10-13 09:55 UTC, IvanShamatov commented on app/controllers/cards_controller.rb
> +  	@cards = Card.all
в руби используются для отступа только пробелы и только 2 штуки
ты можешь это сделать в настройках сублиме по умолчанию

2016-10-13 09:55 UTC, IvanShamatov commented on app/views/cards/index.html.erb
> +</ul>
В posix системах файлы принято заканчивать новой строкой.
Вот этот символ красненький означает, что у тебя нет переноса на новую строку
поставь в конце enter и сохрани файл. Как только ты подключишь houndci у тебя вечно на это будет ругаться. Но заканчивать файл новой строкой — это тоже настройка редактора, её можно тоже добавить в сублиме.

2016-10-13 09:55 UTC, IvanShamatov commented on config/routes.rb
> +  get '/home' => 'home#index'
есть ещё роут root, это то, куда будет отправлен пользователь, если он зашел по localhost:3000/ (на главную)

2016-10-13 09:55 UTC, IvanShamatov commented on db/migrate/20161012194219_create_cards.rb
> +      t.text :original_text
тебе абсолютно ни к чему тут целое поле text, у тебя вряд ли слово или перевод будут длиной больше 255 символов, только память тратишь

2016-10-13 09:55 UTC, IvanShamatov commented on db/migrate/20161012194219_create_cards.rb
> +      t.date :review_date
Это твоё право использовать дату вместо дата+время. Однако для пользовательского опыта гораздо круче если проверенная карточка будет доступна к проверке ровно через 3 дня (об этом в задаче будет дальше), чем через 3 дня + сколько-то там часов до полуночи. НО как я уже сказал — это твоё право, как в этом случае действовать.

2016-10-13 10:00 UTC, IvanShamatov requested changes

2016-10-13 10:00 UTC, IvanShamatov commented on app/views/cards/show.html.erb
> +      <li> <%= Date.parse(@card.review_date.to_s).strftime("%d/%m/%Y") %></li>
то что ты здесь делается — очень странно
ты берешь дату, 
переводишь её в строку
парсишь строку, получаешь дату
применяешь форматирование
почему просто не сделать:
`@card.review_date.strftime("%d/%m/%Y")`

2016-10-13 10:00 UTC, AlinaVasylieva commented on db/migrate/20161012194219_create_cards.rb
> +      t.text :original_text
Окей, меня часто сбивает то, что указано в задании. Я пока что боюсь самодеятельности!  По тому же принципу я назвала поля с большой буквы)))))

2016-10-13 10:02 UTC, AlinaVasylieva commented on app/views/cards/show.html.erb
> +      <li> <%= Date.parse(@card.review_date.to_s).strftime("%d/%m/%Y") %></li>
мне выдало ошибку, что не date can't be implicitly converted to string

2016-10-13 11:46 UTC, AlinaVasylieva commented on config/routes.rb
> +  get '/home' => 'home#index'
разве не localhost:3000/ home - главная?

2016-10-13 11:52 UTC, IvanShamatov requested changes

2016-10-13 11:52 UTC, IvanShamatov commented on config/routes.rb
> +  get '/home' => 'home#index'
ну это какую ты сделаешь, но обычно люди набирают только адрес, и не дописывают home в урле

2016-10-13 11:52 UTC, IvanShamatov commented on app/views/cards/index.html.erb
> +</ul>
EOF (end of file) плохой

2016-10-13 11:52 UTC, IvanShamatov commented on app/views/cards/show.html.erb
> +</section>
EOF плохой

2016-10-13 13:15 UTC, IvanShamatov commented on .rubocop.yml
> +  Enabled: false
EOF!!!

2016-10-13 13:42 UTC, merged